"""Add scheduled_posts table

Revision ID: 6fc3002de473
Revises: 92f375a1882b
Create Date: 2025-07-11 17:39:42.487570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fc3002de473'
down_revision = '92f375a1882b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 予約投稿テーブルを作成
    op.create_table('scheduled_posts',
        sa.Column('id', sa.String(), nullable=False, primary_key=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('image_urls', sa.Text(), nullable=True),
        sa.Column('scheduled_time', sa.DateTime(), nullable=False),
        sa.Column('status', sa.String(), nullable=True),
        sa.Column('bot_id', sa.String(), nullable=False),
        sa.Column('sheet_row_index', sa.Integer(), nullable=True),
        sa.Column('sheet_id', sa.String(), nullable=True),
        sa.Column('twitter_post_id', sa.String(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('posted_at', sa.DateTime(), nullable=True),
        sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
        sa.Column('ai_prompt', sa.Text(), nullable=True),
        sa.Column('source_data_id', sa.String(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=True),
        sa.Column('max_retries', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True)
    )
    
    # SQLiteでは外部キー制約追加をスキップ
    # op.create_foreign_key(None, 'posts', 'posts', ['thread_root_id'], ['id'])
    # op.create_foreign_key(None, 'posts', 'posts', ['parent_post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_posts')
    # ### end Alembic commands ###