"""Add image support to posts table

Revision ID: 92f375a1882b
Revises: c836455b2722
Create Date: 2025-07-11 11:56:13.872808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92f375a1882b'
down_revision = 'c836455b2722'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 画像関連フィールドを追加
    op.add_column('posts', sa.Column('image_urls', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('media_ids', sa.Text(), nullable=True))
    # SQLiteでは外部キー制約追加をスキップ（既に存在するため）
    # op.create_foreign_key(None, 'posts', 'posts', ['parent_post_id'], ['id'])
    # op.create_foreign_key(None, 'posts', 'posts', ['thread_root_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'media_ids')
    op.drop_column('posts', 'image_urls')
    # ### end Alembic commands ###