"""Add bot fields description content_template etc

Revision ID: a811ecac39f4
Revises: 4f46ef0de30d
Create Date: 2025-07-11 10:17:21.582976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a811ecac39f4'
down_revision = '4f46ef0de30d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bots', sa.Column('description', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('content_template', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('posting_interval', sa.String(), nullable=True))
    op.add_column('bots', sa.Column('max_posts_per_day', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bots', 'max_posts_per_day')
    op.drop_column('bots', 'posting_interval')
    op.drop_column('bots', 'content_template')
    op.drop_column('bots', 'description')
    # ### end Alembic commands ###