"""Add api_key and api_secret to twitter_accounts

Revision ID: a95dfd2d0a2b
Revises: c6bc2cf35301
Create Date: 2025-07-11 10:42:09.002368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a95dfd2d0a2b'
down_revision = 'c6bc2cf35301'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('twitter_accounts', sa.Column('api_key', sa.String(), nullable=True))
    op.add_column('twitter_accounts', sa.Column('api_secret', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('twitter_accounts', 'api_secret')
    op.drop_column('twitter_accounts', 'api_key')
    # ### end Alembic commands ###