"""Add twitter_post_id and error_message to posts

Revision ID: c6bc2cf35301
Revises: a811ecac39f4
Create Date: 2025-07-11 10:24:02.148861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6bc2cf35301'
down_revision = 'a811ecac39f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('twitter_post_id', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'error_message')
    op.drop_column('posts', 'twitter_post_id')
    # ### end Alembic commands ###