"""Add thread support to posts table

Revision ID: c836455b2722
Revises: a95dfd2d0a2b
Create Date: 2025-07-11 10:53:50.233690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c836455b2722'
down_revision = 'a95dfd2d0a2b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('parent_post_id', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('thread_root_id', sa.String(), nullable=True))
    op.add_column('posts', sa.Column('thread_order', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('in_reply_to_tweet_id', sa.String(), nullable=True))
    # SQLiteでは外部キー制約追加をスキップ
    # op.create_foreign_key(None, 'posts', 'posts', ['parent_post_id'], ['id'])
    # op.create_foreign_key(None, 'posts', 'posts', ['thread_root_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    # op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'in_reply_to_tweet_id')
    op.drop_column('posts', 'thread_order')
    op.drop_column('posts', 'thread_root_id')
    op.drop_column('posts', 'parent_post_id')
    # ### end Alembic commands ###